export enum PMS{
    /*A nivel de sistema, modulos principales */
    TV_SEE='TV_SEE',
    TD_SEE='TD_SEE',
    SI_SEE='SI_SEE',


    /*Clientes */
    SI_CLIENTS_SEE='SI_CLIENTS_SEE',
    SI_CLIENTS_ADD='SI_CLIENTS_ADD',
    SI_CLIENTS_UPD='SI_CLIENTS_UPD',
    SI_CLIENTS_DEL='SI_CLIENTS_DEL',

    /*Usuarios */
    SI_USERS_SEE='SI_USERS_SEE',

    /*Permisos y roles */
    SI_PERMISSIONS_SEE='SI_PERMISSIONS_SEE',
    SI_PERMISSIONS_ADD='SI_PERMISSIONS_ADD',
    SI_PERMISSIONS_UPD='SI_PERMISSIONS_UPD',
    SI_PERMISSIONS_DEL='SI_PERMISSIONS_DEL',


    /*Modulo linea de espera */
    SI_CALLS_SEE='SI_CALLS_SEE',
    SI_TICKETS_SEE='SI_TICKETS_SEE',
    SI_TELLERS_SEE='SI_TELLERS_SEE',
    SI_CATEGORIES_SEE='SI_CATEGORIES_SEE',
    SI_VIDEOS_SEE='SI_VIDEOS_SEE',
    SI_CARDS_SEE='SI_CARDS_SEE',

    /*Reportes */
    SI_REPORT_WAITING_LINE='SI_REPORT_WAITING_LINE',
    SI_REPORT_CLIENT_SEE='SI_REPORT_CLIENT_SEE',
    
}

