export enum PMS{
    /*A nivel de sistema, modulos principales */
    TV_SEE='TV_SEE',
    TD_SEE='TD_SEE',
    SI_SEE='SI_SEE',

    /*Clientes */
    SI_CLIENTS_SEE='SI_CLIENTS_SEE',
    SI_CLIENTS_ADD='SI_CLIENTS_ADD',
    SI_CLIENTS_UPD='SI_CLIENTS_UPD',
    SI_CLIENTS_DEL='SI_CLIENTS_DEL',

    /*Usuarios */
    SI_USERS_SEE='SI_USERS_SEE',
    SI_USERS_ADD='SI_USERS_ADD',
    SI_USERS_UPD='SI_USERS_UPD',
    SI_USERS_DEL='SI_USERS_DEL',

    /*Permisos y roles */
    SI_PERMISSIONS_SEE='SI_PERMISSIONS_SEE',
    SI_PERMISSIONS_ADD='SI_PERMISSIONS_ADD',
    SI_PERMISSIONS_UPD='SI_PERMISSIONS_UPD',
    SI_PERMISSIONS_DEL='SI_PERMISSIONS_DEL',


    /* Permisos de sede*/
    SI_HEADQUARTER_SEE='SI_HEADQUARTER_SEE',
    SI_HEADQUARTER_ADD='SI_HEADQUARTER_ADD',
    SI_HEADQUARTER_UPD='SI_HEADQUARTER_UPD',
    SI_HEADQUARTER_DEL='SI_HEADQUARTER_DEL',


    /*Modulo linea de espera */
    SI_CALLS_SEE='SI_CALLS_SEE',
    SI_TICKETS_SEE='SI_TICKETS_SEE',
    SI_TELLERS_SEE='SI_TELLERS_SEE',
    SI_CATEGORIES_SEE='SI_CATEGORIES_SEE',
    SI_VIDEOS_SEE='SI_VIDEOS_SEE',
    SI_CARDS_SEE='SI_CARDS_SEE',

    /*Reportes */
    SI_REPORT_WAITING_LINE='SI_REPORT_WAITING_LINE',
    SI_REPORT_CLIENT_SEE='SI_REPORT_CLIENT_SEE',

    /*Profile */
    SI_PROFILE_SEE='SI_PROFILE_SEE',

    /*Permisos añadidos el 01/01/2023 */
    SI_ACCOUNTING_MODULE='SI_ACCOUNTING_MODULE',
    SI_ACCOUNTING_SEE='SI_ACCOUNTING_SEE',
    SI_ACCOUNTING_XLS_DWL='SI_ACCOUNTING_XLS_DWL',
    SI_DEBTS_AND_PAIDS_SEE='SI_DEBTS_AND_PAIDS_SEE',
    SI_DEBTS_AND_PAIDS_XLS_DWL='SI_DEBTS_AND_PAIDS_XLS_DWL',
    SI_LAST_PAYMENT_BY_CLIENT_SEE='SI_LAST_PAYMENT_BY_CLIENT_SEE',
    SI_LAST_PAYMENT_BY_CLIENT_XLS_DWL='SI_LAST_PAYMENT_BY_CLIENT_XLS_DWL',
    SI_OLD_DEBT_BY_CLIENT_SEE='SI_OLD_DEBT_BY_CLIENT_SEE',
    SI_OLD_DEBT_BY_CLIENT_XLS_DWL='SI_OLD_DEBT_BY_CLIENT_XLS_DWL',
    SI_CLIENTS_XLS_DWL='SI_CLIENTS_XLS_DWL',

    /*Cambios 07/01/2023 */
    SI_REPORT_MODULE='SI_REPORT_MODULE',
    SI_REPORT_WAITING_LINE_GRAPH='SI_REPORT_WAITING_LINE_GRAPH',
    SI_REPORT_ACCOUNTING_GRAPH='SI_REPORT_ACCOUNTING_GRAPH',
    SI_REPORT_CLIENTS_GRAPH='SI_REPORT_CLIENTS_GRAPH'
}

