import { ParentInterface } from "./parent.interface";


export interface SocketInterface  <T extends ParentInterface> extends ParentInterface {
    action: SOCKET_ACTION,
    data:T[] | T | null
}

export enum SOCKET_ACTION{
    TV_ADD_TARGET_CALL=1,
    TV_UPD_TARGET_CALL=2,
    TV_REFRESH_TARGET_CALL=3,
    TV_REMOVE_TARGET_CALL=4,

    WAITING_LINE_ADD_APPOINTMENT=5,
    
    SEND_PDF_LINK_TO_PRINTER=6,
    PRINTER_IS_ENABLE=7,
    PRINTER_READY_TO_PRINT=8,
    RESPONSE_FROM_PRINT_SERVER=9, 
    
    TV_SEND_VIDEO_TO_PLAY=10,

    TV_PLAY_VIDEO_REMOTO=11, 
    TV_PAUSE_VIDEO_REMOTO=12,
    TV_STOP_VIDEO_REMOTO=13,
    TV_NEXT_VIDEO_REMOTO=14,
    TV_PREVIOUS_VIDEO_REMOTO=15,

    TV_SET_VOLUME_VIDEO_REMOTO=16,
    TV_RELOAD_VIDEOS_REMOTO=17,
    
    TV_ADD_VIDIO_TO_LIST=18

}
